name: build


on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - develop
      - main
      - 'release/**'
    paths:
      - 'Sources/**'
      - 'Examples/**'
      - 'Tests/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 20 * * 5'


jobs:
  build:
    uses: madmachineio/actions/.github/workflows/build.yml@main